name: Run Ansible

permissions:
 contents: read

on: 
    workflow_dispatch:
        inputs:
            CM-Check:
                description: "Which CM ?"
                required: true
                type: string

jobs:
  
    Ansible:
        name: Ansible 
        continue-on-error: false
        runs-on: self-hosted
        steps:
            - name: install
              run: |
                pip install ansible jmespath
                ansible-playbook yaml/ansible/iptables-playbook.yml

    