name: Run Ansible

permissions:
 contents: read

on: 
    workflow_dispatch:
        inputs:
            CM-Check:
                description: "Which CM ?"
                required: true
                type: string

jobs:
  
    Ansible:
        name: Ansible 
        continue-on-error: false
        runs-on: self-hosted
        steps:
            - name: install
              run: |
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                python get-pip.py
                pip install ansible jmespath

    