name: Lint Playbook

permissions:
 contents: read

on: 
    pull_request:
       branches:
        - '*'

jobs:
  
    AnsibleLint:
        name: Ansible Lint
        continue-on-error: false
        runs-on: ubuntu-latest
        steps:
            - name: checkout-stuff
              uses: actions/checkout@v4 #Must have the "v" for  version  
            - name: install requirements 
              run: |
                python3 -m venv gha-run
                source gha-run/bin/activate
                pip install --upgrade pip
                pip install ansible-core ansible-lint
                ansible-lint yaml/ansible/*

    
