name: K8 config

permissions:
 contents: read

on: 
    workflow_dispatch:
        inputs:
            CM-Check:
                description: "Which CM ?"
                required: true
                type: string

jobs:
  
    check-input:
        name: Check Input
        continue-on-error: false
        runs-on: self-hosted
        env:
            CM: ${{inputs.CM-Check}}
        steps:
            - name: Check Input
              run: |
                echo $CM
    
    get-cm:
        name: Get Config Map
        continue-on-error: false
        runs-on: self-hosted
        needs: [check-input]
        steps:
            - name: checkout-stuff
              uses: actions/checkout@v4 #Must have the "v" for  version 
            - name: Get Dyff
              run: |
                wget  https://github.com/homeport/dyff/releases/download/v1.12.0/dyff_1.12.0_linux_amd64.tar.gz 2> /dev/null
                tar -zvxf dyff_1.12.0_linux_amd64.tar.gz 
                chmod +x dyff
            - name: Get CM
              run: |
                curl  https://github.com/homeport/dyff/releases/download/v1.12.0/dyff_1.12.0_linux_arm64.tar.gz > dyff.tar.gz
                tar -zvxf dyff.tar.gz
                chmod +x dyff
                kubectl get cm kube-proxy -n kube-system -o=yaml > kube-proxy-`date +%F`.yml
            - name: diff
              run: |
                diff yaml/kube-proxy.yml kube-proxy-`date +%F`.yml
